import type { NodeCategory, PortDefinition, Z8NodeData } from "@/types/flow";
import {
  AlignLeft,
  ArrowRightLeft,
  Bot,
  Braces,
  Brain,
  Bug,
  Calculator,
  Clock,
  Code,
  Database,
  FileSpreadsheet,
  FileText,
  Filter,
  Fingerprint,
  GitBranch,
  Globe,
  Headphones,
  Image,
  Layers,
  MessageSquare,
  Mic,
  Phone,
  Radio,
  Repeat,
  Scissors,
  Send,
  ShieldCheck,
  Split,
  Tags,
  Timer,
  UserCheck,
  Volume2,
  Webhook,
  Zap,
} from "lucide-react";

/** Centralized icon registry - add new icons here only. */
export const NODE_ICON_MAP: Record<
  string,
  React.ComponentType<{ size?: number; className?: string }>
> = {
  Globe,
  ArrowRightLeft,
  Clock,
  Webhook,
  Code,
  Braces,
  Filter,
  Bug,
  Send,
  GitBranch,
  Timer,
  Database,
  Radio,
  Brain,
  Fingerprint,
  Tags,
  FileText,
  Scissors,
  AlignLeft,
  Bot,
  Image,
  FileSpreadsheet,
  Calculator,
  Layers,
  Phone,
  MessageSquare,
  Mic,
  Volume2,
  Headphones,
  UserCheck,
  ShieldCheck,
  Zap,
  Split,
  Repeat,
};

export interface NodeDefinition {
  type: string;
  label: string;
  category: NodeCategory;
  icon: string;
  description: string;
  inputs: PortDefinition[];
  outputs: PortDefinition[];
  defaultConfig: Record<string, unknown>;
}

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // Input nodes
  {
    type: "http-in",
    label: "HTTP In",
    category: "input",
    icon: "Globe",
    description: "Receive HTTP requests",
    inputs: [],
    outputs: [{ id: "response", name: "Response", type: "object" }],
    defaultConfig: { method: "POST", path: "/" },
  },
  {
    type: "timer",
    label: "Timer",
    category: "input",
    icon: "Clock",
    description: "Trigger on interval",
    inputs: [],
    outputs: [{ id: "tick", name: "Tick", type: "object" }],
    defaultConfig: { interval: 5000, unit: "ms" },
  },
  {
    type: "webhook",
    label: "Webhook",
    category: "input",
    icon: "Webhook",
    description: "Listen for webhook events",
    inputs: [],
    outputs: [{ id: "payload", name: "Payload", type: "object" }],
    defaultConfig: { path: "/hook", method: "POST" },
  },
  {
    type: "cron-trigger",
    label: "Cron Trigger",
    category: "input",
    icon: "Zap",
    description: "Trigger flows on a schedule (cron expressions)",
    inputs: [],
    outputs: [{ id: "output", name: "Output", type: "object" }],
    defaultConfig: {
      cron: "0 * * * *",
      timezone: "UTC",
      payload: {},
    },
  },
  {
    type: "webhook-trigger",
    label: "Webhook Trigger",
    category: "input",
    icon: "Webhook",
    description: "Trigger flow on incoming HTTP request with auth",
    inputs: [],
    outputs: [{ id: "output", name: "Output", type: "object" }],
    defaultConfig: {
      method: "POST",
      path: "",
      authType: "none",
      authToken: "",
      responseMode: "last_node",
    },
  },

  // Process nodes
  {
    type: "function",
    label: "Function",
    category: "process",
    icon: "Code",
    description:
      "Transform or pass through the message using a template / output value (not executed as JavaScript)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [{ id: "output", name: "Output", type: "any" }],
    defaultConfig: { code: "msg", language: "text" },
  },
  {
    type: "json",
    label: "JSON Transform",
    category: "process",
    icon: "Braces",
    description: "Parse or stringify JSON",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [{ id: "output", name: "Output", type: "object" }],
    defaultConfig: { action: "parse" },
  },
  {
    type: "http-request",
    label: "HTTP Request",
    category: "process",
    icon: "Send",
    description: "Make HTTP requests to external APIs",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "response", name: "Response", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      url: "https://httpbin.org/post",
      method: "POST",
      headers: {},
      bodyPath: "req.body",
      timeout: 5000,
    },
  },
  {
    type: "filter",
    label: "Filter",
    category: "process",
    icon: "Filter",
    description: "Filter messages by condition",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "pass", name: "Pass", type: "any" },
      { id: "reject", name: "Reject", type: "any" },
    ],
    defaultConfig: {
      property: "req.body.age",
      condition: "gte",
      value: 18,
      passExpression: "",
      rejectExpression: "",
    },
  },

  // Output nodes
  {
    type: "debug",
    label: "Debug",
    category: "output",
    icon: "Bug",
    description: "Log messages to debug panel",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [],
    defaultConfig: { output: "full", console: false },
  },
  {
    type: "http-out",
    label: "HTTP Response",
    category: "output",
    icon: "Send",
    description: "Send HTTP response",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [],
    defaultConfig: { statusCode: 200 },
  },

  // Logic nodes
  {
    type: "switch",
    label: "Switch",
    category: "logic",
    icon: "GitBranch",
    description: "Route by condition",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "out1", name: "Case 1", type: "any" },
      { id: "out2", name: "Case 2", type: "any" },
      { id: "default", name: "Default", type: "any" },
    ],
    defaultConfig: {
      property: "req.body.action",
      rules: [
        { type: "eq", value: "create", port: "out1" },
        { type: "eq", value: "update", port: "out2" },
      ],
    },
  },
  {
    type: "if-else",
    label: "If/Else",
    category: "logic",
    icon: "Split",
    description: "Conditional routing: evaluate field and route to true/false",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "true", name: "True", type: "any" },
      { id: "false", name: "False", type: "any" },
    ],
    defaultConfig: {
      field: "payload.status",
      operator: "==",
      value: "success",
      trueExpression: "",
      falseExpression: "",
    },
  },
  {
    type: "loop",
    label: "Loop",
    category: "logic",
    icon: "Repeat",
    description: "Iterate over arrays, emitting one message per item",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "item", name: "Item", type: "any" },
      { id: "done", name: "Done", type: "object" },
    ],
    defaultConfig: {
      field: "payload.items",
      itemExpression: "",
    },
  },
  {
    type: "delay",
    label: "Delay",
    category: "logic",
    icon: "Timer",
    description: "Delay message delivery",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [{ id: "output", name: "Output", type: "any" }],
    defaultConfig: { delay: 1000, unit: "ms" },
  },

  // Data nodes
  {
    type: "database",
    label: "Database",
    category: "data",
    icon: "Database",
    description: "Query a database",
    inputs: [{ id: "query", name: "Query", type: "string" }],
    outputs: [
      { id: "results", name: "Results", type: "array" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      dbType: "postgres",
      host: "localhost",
      port: 5432,
      database: "",
      user: "",
      password: "",
      query: "",
      params: [],
    },
  },
  {
    type: "mqtt",
    label: "MQTT",
    category: "data",
    icon: "Radio",
    description: "Publish/subscribe to MQTT broker",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "message", name: "Message", type: "object" },
      { id: "published", name: "Published", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "publish",
      broker: "localhost",
      port: 1883,
      topic: "z8run/default",
      qos: 0,
      clientId: "",
      username: "",
      password: "",
      useTls: false,
      keepAlive: 30,
      timeout: 30000,
    },
  },

  // Data Engineering nodes
  {
    type: "csv",
    label: "CSV",
    category: "data",
    icon: "FileSpreadsheet",
    description: "Parse CSV to JSON or stringify JSON to CSV",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "output", name: "Output", type: "any" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "parse",
      delimiter: ",",
      hasHeaders: true,
      columns: [],
    },
  },
  {
    type: "aggregator",
    label: "Aggregator",
    category: "data",
    icon: "Calculator",
    description: "Aggregate data: count, sum, avg, min, max, group by",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "output", name: "Output", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      operation: "count",
      field: "",
      groupBy: "",
    },
  },
  {
    type: "batch",
    label: "Batch",
    category: "process",
    icon: "Layers",
    description: "Split arrays into chunks for batch processing",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "output", name: "Output", type: "array" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      size: 100,
      field: "",
    },
  },

  {
    type: "mapper",
    label: "Mapper",
    category: "process",
    icon: "ArrowRightLeft",
    description: "Pick, rename, and reshape fields from the payload",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [{ id: "output", name: "Output", type: "object" }],
    defaultConfig: {
      mappings: [{ from: "", to: "" }],
      passThrough: false,
    },
  },

  // Security nodes
  {
    type: "sanitize",
    label: "Sanitize",
    category: "security",
    icon: "ShieldCheck",
    description: "Remove or mask sensitive data (tokens, emails, cards, IPs)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [{ id: "output", name: "Output", type: "object" }],
    defaultConfig: {
      fields: "",
      strategy: "mask",
      detectPatterns: true,
      patterns: "credit_card,email,bearer_token,phone,ip_address",
    },
  },

  // AI nodes
  {
    type: "llm",
    label: "LLM",
    category: "ai",
    icon: "Brain",
    description:
      "AI language model with vision support (OpenAI, Anthropic, Ollama)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "response", name: "Response", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "gpt-4o-mini",
      apiKey: "",
      baseUrl: "",
      systemPrompt: "",
      temperature: 0.7,
      maxTokens: 1024,
      vision: false,
      timeout: 30000,
    },
  },
  {
    type: "embeddings",
    label: "Embeddings",
    category: "ai",
    icon: "Fingerprint",
    description: "Generate vector embeddings from text",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "embedding", name: "Embedding", type: "array" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "text-embedding-3-small",
      apiKey: "",
      baseUrl: "",
      timeout: 15000,
    },
  },
  {
    type: "classifier",
    label: "Classifier",
    category: "ai",
    icon: "Tags",
    description: "Classify text into categories using AI",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "result", name: "Result", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "gpt-4o-mini",
      apiKey: "",
      baseUrl: "",
      categories: "positive,negative,neutral",
      context: "",
      timeout: 15000,
    },
  },
  {
    type: "prompt-template",
    label: "Prompt Template",
    category: "ai",
    icon: "FileText",
    description: "Render templates with {{variable}} injection",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "output", name: "Output", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      template: "Hello {{name}}, you asked: {{prompt}}",
      strictMode: false,
    },
  },
  {
    type: "text-splitter",
    label: "Text Splitter",
    category: "ai",
    icon: "Scissors",
    description: "Split text into chunks for RAG pipelines",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "chunks", name: "Chunks", type: "array" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      strategy: "fixed",
      chunkSize: 512,
      overlap: 50,
      separator: "",
    },
  },
  {
    type: "vector-store",
    label: "Vector Store",
    category: "ai",
    icon: "Database",
    description: "Store and search vector embeddings",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "stored", name: "Stored", type: "object" },
      { id: "results", name: "Results", type: "array" },
      { id: "deleted", name: "Deleted", type: "object" },
      { id: "cleared", name: "Cleared", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "store",
      collection: "default",
      topK: 5,
      minScore: 0.0,
    },
  },
  {
    type: "structured-output",
    label: "Structured Output",
    category: "ai",
    icon: "Braces",
    description: "Force LLM output into JSON schema",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "output", name: "Output", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "gpt-4o-mini",
      apiKey: "",
      baseUrl: "",
      schema:
        '{"type":"object","properties":{"name":{"type":"string"},"score":{"type":"number"}}}',
      retries: 2,
      timeout: 30000,
    },
  },
  {
    type: "summarizer",
    label: "Summarizer",
    category: "ai",
    icon: "AlignLeft",
    description: "Summarize text with map-reduce for long docs",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "summary", name: "Summary", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "gpt-4o-mini",
      apiKey: "",
      baseUrl: "",
      strategy: "simple",
      maxLength: 200,
      language: "",
      timeout: 60000,
    },
  },
  {
    type: "ai-agent",
    label: "AI Agent",
    category: "ai",
    icon: "Bot",
    description: "LLM agent with tool-use capabilities",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "response", name: "Response", type: "object" },
      { id: "tool_call", name: "Tool Call", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "gpt-4o",
      apiKey: "",
      baseUrl: "",
      systemPrompt: "You are a helpful assistant.",
      tools: "[]",
      maxIterations: 5,
      temperature: 0.7,
      timeout: 60000,
    },
  },
  {
    type: "image-gen",
    label: "Image Gen",
    category: "ai",
    icon: "Image",
    description: "Generate images with DALL-E or Stability AI",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "image", name: "Image", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "dall-e-3",
      apiKey: "",
      baseUrl: "",
      size: "1024x1024",
      quality: "standard",
      style: "vivid",
      timeout: 60000,
    },
  },

  // Communication nodes
  {
    type: "twilio",
    label: "Twilio",
    category: "communication",
    icon: "Phone",
    description: "Send SMS, make calls, lookup numbers via Twilio",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "sent", name: "Sent", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "sms",
      accountSid: "",
      authToken: "",
      fromNumber: "",
      timeout: 10000,
    },
  },
  {
    type: "whatsapp",
    label: "WhatsApp",
    category: "communication",
    icon: "MessageSquare",
    description: "Send messages via WhatsApp Business API",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "sent", name: "Sent", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "send_text",
      phoneNumberId: "",
      accessToken: "",
      apiVersion: "v18.0",
      timeout: 10000,
    },
  },
  {
    type: "stt",
    label: "Speech to Text",
    category: "communication",
    icon: "Mic",
    description: "Convert audio to text (Whisper, Deepgram, Google)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "transcript", name: "Transcript", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "whisper-1",
      apiKey: "",
      language: "",
      timeout: 30000,
    },
  },
  {
    type: "tts",
    label: "Text to Speech",
    category: "communication",
    icon: "Volume2",
    description: "Convert text to audio (OpenAI, ElevenLabs, Google)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "audio", name: "Audio", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "openai",
      model: "tts-1",
      apiKey: "",
      voice: "alloy",
      timeout: 30000,
    },
  },
  {
    type: "conversation-memory",
    label: "Conversation Memory",
    category: "communication",
    icon: "Headphones",
    description: "Store and retrieve conversation history",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "saved", name: "Saved", type: "object" },
      { id: "history", name: "History", type: "object" },
      { id: "listed", name: "Listed", type: "array" },
      { id: "cleared", name: "Cleared", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "save",
      maxMessages: 50,
      ttlSeconds: 3600,
    },
  },
  {
    type: "crm",
    label: "CRM",
    category: "communication",
    icon: "UserCheck",
    description: "Manage contacts and deals (HubSpot, Salesforce)",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "result", name: "Result", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      provider: "hubspot",
      action: "create_contact",
      apiKey: "",
      baseUrl: "",
      timeout: 15000,
    },
  },
  {
    type: "human-handoff",
    label: "Human Handoff",
    category: "communication",
    icon: "ShieldCheck",
    description: "Escalate conversations to human agents",
    inputs: [{ id: "input", name: "Input", type: "any" }],
    outputs: [
      { id: "escalated", name: "Escalated", type: "object" },
      { id: "status", name: "Status", type: "object" },
      { id: "assigned", name: "Assigned", type: "object" },
      { id: "resolved", name: "Resolved", type: "object" },
      { id: "error", name: "Error", type: "any" },
    ],
    defaultConfig: {
      action: "escalate",
      priority: "medium",
      webhookUrl: "",
      timeout: 10000,
    },
  },
];

export const NODE_CATEGORIES: { id: NodeCategory; label: string }[] = [
  { id: "input", label: "Input" },
  { id: "process", label: "Process" },
  { id: "output", label: "Output" },
  { id: "logic", label: "Logic" },
  { id: "data", label: "Data" },
  { id: "ai", label: "AI" },
  { id: "communication", label: "Communication" },
  { id: "security", label: "Security" },
];

/** Create Z8NodeData from a NodeDefinition */
export function createNodeData(def: NodeDefinition): Z8NodeData {
  return {
    label: def.label,
    type: def.type,
    category: def.category,
    icon: def.icon,
    config: { ...def.defaultConfig },
    status: "idle",
    inputs: def.inputs,
    outputs: def.outputs,
  };
}
